'Speak Out':
  # Media
  - description: 'Look up media outlets in your area'
  - description: 'Email reporters and media outlets 3-7 days before the event'
  - description: 'Call reporters and media to make sure they know about the event'
  - description: 'Arrive early to greet media representatives'
  - description: 'Send media release and photos to media representatives'
  # Materials
  - description: 'Make 5 signs that showcase your message and arrive early to distribute them'
  - description: 'Make 15 signs that showcase your message and arrive early to distribute them'
  - description: 'Make 30 signs that showcase your message and arrive early to distribute them'
  - description: 'Make petition sheets for attendees'
  - description: 'Bring lots of extra pens and clipboards or other hard surfaces to write on'
  # Recruitment
  - description: 'Print and post recruitment fliers in public places'
  - description: 'Recruit 5-10 of your friends to come'
  - description: 'Contacted like-minded organizations and invite them'
  - description: 'Publicize your event via social media'
 
'Rally':
  # Media
  - description: 'Look up media outlets in your area'
  - description: 'Email reporters and media outlets 3-7 days before the event'
  - description: 'Call reporters and media to make sure they know about the event'
  - description: 'Arrive early to greet media representatives'
  - description: 'Send media release and photos to media representatives'
  # Signs
  - description: 'Make 5 signs that showcase your message and arrive early to distribute them'
  - description: 'Make 15 signs that showcase your message and arrive early to distribute them'
  - description: 'Make 30 signs that showcase your message and arrive early to distribute them'
  # Recruitment
  - description: 'Print and post recruitment fliers in public places'
  - description: 'Recruit 5-10 of your friends to come'
  - description: 'Contacted like-minded organizations and invite them to the rally'
  - description: 'Publicize your event via social media'
 
