-
  name: "The Congolese Tragedy: From Causes to Sustainable Solutions"
  address: "720 Rutland Avenue"
  city: "Baltimore"
  zip: "21205"
  state: "MD"
  event_type_id: 3
  approved: true
  description: "We will be screening The Congolese Tragedy: From Causes to Sustainable Solutions, a hallmark synthesis about the situation in the Congo."
  notes: "Thanks for attending! We'll all be wearing red to this event to show our solidarity."

-
  name: "The Crisis of Sexual Violence and Rape as a Weapon of War"
  address: "152 Pearl Street"
  city: "Burlington"
  zip: "05401"
  state: "VT"
  event_type_id: 4
  approved: true
  description: "We will be discussing the use of sexual violence and rape as a weapon of war by genocide perpetrators in the Congo."
  notes: "Thanks for attending! We'll all be wearing red to this event to show our solidarity."
