development:
  adapter: postgresql
  database: db/rally_development
  template: template0
  pool: 5
  timeout: 5000
  username: postgres 
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: db/rally_test
  template: template0
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  database: db/rally_production
  pool: 5
  timeout: 5000
  username:
  password:

