fotc_coordinator:
  email: "coordinator@friendsofthecongo.org"
  name: "FOTC Coordinator"
  password: "password"
  password_confirmation: "password"

fotc:
  name: "Friends of the Congo" 
  tagline: "Crisis in the Congo: Uncovering the Truth"
  call_to_action: "Raising consciousness about the challenge of the Congo and supporting Congolese institutions as they strive to bring about peaceful and lasting change"
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "Imagine that millions have been killed and continue to die, hundreds of thousands of women have been systematically raped and are still being brutalized, corporate plundering reigns, the 2nd largest rainforest in the world, being destroyed and mass crimes have been committed and remain widespread - yet the world has been deadly silent. This is modern-day Congo. Join the global movement - Break the Silence!"
  location: "Global"

fotc_event1:
  name: "Screening Crisis in the Congo: Building Solidarity in Southern Africa"
  address: "200 E Randolph St"
  city: "Chicago"
  zip: "60634"
  state: "IL"
  event_type_id: 1
  approved: true

fotc_event2:
  name: "Breaking the Silence for Congo Women"
  address: "265 Chatham Drive"
  city: "Chapel Hill"
  zip: "27516"
  state: "NC"
  event_type_id: 3
  approved: true

fotc_event3:
  name: "Screening Crisis in the Congo: Uncovering the Truth"
  address: "409 Riverside Drive"
  city: "New York"
  zip: "10027"
  state: "NY"
  event_type_id: 4
  approved: true

 
fotc_event4:
  name: "Discussion: Conflict Minerals in the Congo"
  address: "240 E. 2nd St"
  city: "Elmhurst"
  zip: "60126"
  state: "IL"
  event_type_id: 3
  approved: true

fotc_event5:
  name: "Screening Crisis in the Congo: Uncovering the Truth"
  address: "3805 N Linden Lane"
  city: "Peoria"
  zip: "61614"
  state: "IL"
  event_type_id: 4
  approved: true

sub_movement1:  
  name: "Iowa University Chapter"
  tagline: "Iowa University supports justice in the Congo."
  call_to_action: "Each and everyone of us can do something to bring an end to the suffering in the Congo and work with our Congolese brothers and sisters to bring about change."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement2:
 name: "Northeastern University"
 tagline: "We support peace in the Congo!"
 call_to_action: "We encourage you to bring your talents, skills, expertise, interests, knowledge to be a part of the global movement in support of the Congo"
 published: true
 video: "89rKdJjumdA"
 extended_description: "An historic opportunity exists for ordinary people throughout the globe to participate in a global movement in partnership with the Congolese people as they strive to establish a peaceful and prosperous Congo wherein current and future generations are able to fulfill their enormous human and natural potential."
 location: "Global" 

sub_movement3:
  name: "Berkeley College Chapter"
  tagline: "Supporting justice in the Congo since 2003."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement4:
  name: "Miami University Chapter"
  tagline: "Supporting justice in the Congo since 2003."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement5:
  name: "Unitarian Church of Pompadou Chapter"
  tagline: "Supporting justice in the Congo."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement6:
  name: "Active Transport Alliance Chapter"
  tagline: "The ATA supports justice in the Congo!"
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement7:
  name: "Loosely Federated Musicians Chapter"
  tagline: "Jam for Justice in the Congo."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement8:
  name: "North Carolina College Chapter"
  tagline: "Supporting justice in the Congo."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement9:
  name: "Broadway Theater Group Chapter"
  tagline: "Using theater to spread awareness of the Congo crisis."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

sub_movement10:
  name: "Activist Bicyclists Chapter"
  tagline: "Mobilize for justice in the Congo!"
  call_to_action: "Let's ride to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

