-  
  name: "Iowa University"
  tagline: "Iowa University supports justice in the Congo."
  call_to_action: "Each and everyone of us can do something to bring an end to the suffering in the Congo and work with our Congolese brothers and sisters to bring about change."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
 name: "Northeastern University"
 tagline: "We support peace in the Congo!"
 call_to_action: "We encourage you to bring your talents, skills, expertise, interests, knowledge to be a part of the global movement in support of the Congo"
 published: true
 video: "89rKdJjumdA"
 extended_description: "An historic opportunity exists for ordinary people throughout the globe to participate in a global movement in partnership with the Congolese people as they strive to establish a peaceful and prosperous Congo wherein current and future generations are able to fulfill their enormous human and natural potential."
 location: "Global" 

-
  name: "Berkeley College"
  tagline: "Supporting justice in the Congo since 2003."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "Miami University"
  tagline: "Supporting justice in the Congo since 2003."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "Unitarian Church of Pompadou"
  tagline: "Supporting justice in the Congo."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "Active Transport Alliance"
  tagline: "The ATA supports justice in the Congo!"
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "Loosely Federated Musicians"
  tagline: "Jam for Justice in the Congo."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "North Carolina College"
  tagline: "Supporting justice in the Congo."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "Broadway Theater Group"
  tagline: "Using theater to spread awareness of the Congo crisis."
  call_to_action: "Let's unite to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

-
  name: "Activist Bicyclists"
  tagline: "Mobilize for justice in the Congo!"
  call_to_action: "Let's ride to end suffering in the Congo and bring about lasting positive institutions."
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "People throughout the globe are taking action and Friends of Congo is amassing the diverse actions to build a unified global movement in support of the Congo. Youth in Japan have organized forums, students in New Zealand have held demonstrations and cell outs, activists in California have passed resolutions in their city councils, house wives in Minnesota have raised funds, grandmothers in Tennessee have written to corporations, professionals in Washington State have divested from bad acting corporations, musicians in Columbia South America have written songs, journalists in Sweden have translated documents and much more is happening than we can list on this page."
  location: "Global"

