fotc_coordinator:
  email: "coordinator@friendsofthecongo.org"
  name: "FOTC Coordinator"
  password: "password"
  password_confirmation: "password"

fotc:
  name: "Congo Week"
  tagline: "Crisis in the Congo: Uncovering the Truth"
  call_to_action: "Raising consciousness about the challenge of the Congo and supporting Congolese institutions as they strive to bring about peaceful and lasting change"
  published: true
  video: "vLV9szEu9Ag"
  extended_description: "Imagine that millions have been killed and continue to die, hundreds of thousands of women have been systematically raped and are still being brutalized, corporate plundering reigns, the 2nd largest rainforest in the world, being destroyed and mass crimes have been committed and remain widespread - yet the world has been deadly silent. This is modern-day Congo. Join the global movement - Break the Silence!"
  location: "Global"
