'Rally': 
  - 'Find a location. Ideally your location has something to do with your movement AND will be a good place for media outlets to come cover your event. '
  - 'Pick a date and time. This may already be chosen for you as part of a larger “Day of Action” - if not, try to pick a date and time when both concerned individuals and the media will be able to attend. '
  - 'Create an agenda for your event. This doesn’t need to be perfect - just think about what you want your event to look like and how you want it to flow. It could be “Opening Speaker, Chants, Speaker, March, Closing Speaker.” '
  - 'Find a speaker (maybe it’s you!) and start preparing your speaker for the event.'
  - 'Begin publicizing your event by printing and distributing posters, using social media, inviting friends and family, and contacting like-minded organizations'
  - 'Contact the media about your event'

'Speak Out':
  - 'Find a location. For this type of event, you want to pick a place with lots of food-traffic. '
  - 'Pick a date and time. This may already be chosen for you as part of a larger “Day of Action” - if not, try to pick a date and time when lots of people will be out - lunch time is often a good bet. '
  - 'Create an agenda for your event. This doesn’t need to be perfect - just think about what you want your event to look like and how you want it to flow. It could be “Opening Speaker [probably you], Sharing Stories by Attendees, Pass out Petitions, Petition for 20 minutes-2 hours, Closing Speaker.” '
  - 'Prepare your speaker for the event'
  - 'Begin publicizing your event by printing and distributing posters, using social media, inviting friends and family, and contacting like-minded organizations'
  - 'Contact the media about your event'


