'Rally': 
  - 'Find a location. Ideally your location has something to do with your movement AND will be a good place for media outlets to come cover your event. '
  - 'Pick a date and time. This may already be chosen for you as part of a larger “Day of Action” - if not, try to pick a date and time when both concerned individuals and the media will be able to attend. '
  - 'Create an agenda for your event. This doesn’t need to be perfect - just think about what you want your event to look like and how you want it to flow. It could be “Opening Speaker, Chants, Speaker, March, Closing Speaker.” '
  - 'Find a speaker (maybe it’s you!) and start preparing your speaker for the event.'
  - 'Begin publicizing your event by printing and distributing posters, using social media, inviting friends and family, and contacting like-minded organizations'
  - 'Contact the media about your event'

'Public speak out':
  - 'Find a location. For this type of event, you want to pick a place with lots of food-traffic. '
  - 'Pick a date and time. This may already be chosen for you as part of a larger “Day of Action” - if not, try to pick a date and time when lots of people will be out - lunch time is often a good bet. '
  - 'Create an agenda for your event. This doesn’t need to be perfect - just think about what you want your event to look like and how you want it to flow. It could be “Opening Speaker [probably you], Sharing Stories by Attendees, Pass out Petitions, Petition for 20 minutes-2 hours, Closing Speaker.” '
  - 'Prepare your speaker for the event'
  - 'Begin publicizing your event by printing and distributing posters, using social media, inviting friends and family, and contacting like-minded organizations'
  - 'Contact the media about your event'

'Movie screening':
  - 'Find a location. Make sure it has the seating (or potential for seating) and technology you need.'
  - 'Secure the movie.' 
  - 'Pick a date and time. This may already be chosen for you as part of a larger “Day of Action” - if not, try to pick a date and time when lots of people will be available - probably a weekday evening or weekend afternoon.'
  - 'If you’re doing more than just the movie, create an agenda for your event. This doesn’t need to be perfect - just think about what you want your event to look like and how you want it to flow. It could be “Opening Speaker [probably you], Movie Showing, Call to Action (like petitions or announcements about upcoming events), Closing.”' 
  - 'Begin publicizing your event and recruiting attendees (you can do any or all of the following):'
  - 'Print posters and put them in public places'
  - 'Post your event on social media'
  - 'Call your friends and family and invite them to attend'
  - 'Call and email like-minded organizations and ask them to attend'
  - 'Optional! Snacks'

'Public forum':
  - 'Find a location. Make sure it has the seating (or potential for seating) and potential technology you need (like microphones).'
  - 'Pick a date and time. Try to pick a date and time when lots of people will be available - probably a weekday evening or weekend afternoon. (You should also take into consideration speakers schedules here - if 1 or 2 speakers are truly crucial to your event, get their availability before scheduling.)'
  - 'Secure 3-5 speakers. Make sure you have several perspectives represented - for example, if you are hosting a forum about mountain top removal, you may want an environmental organizer, a union-worker, a doctor, and a supportive elected official. These speakers should be high-level enough to draw interest from your community. If you expect a high turn out and/or any controversy, you may also want to find someone to moderate the panel and direct audience questions.'
  - 'Create an agenda for your event and share the agenda with your event participants.'
  - 'Begin publicizing your event and recruiting attendees (you can do any or all of the following)' 
  - 'Print posters and put them in public places'
  - 'Post your event on social media'
  - 'Call your friends and family and invite them to attend'
  - 'Call and email like-minded organizations and ask them to attend'
  - 'Optional: Snacks!'

'Meet with decision maker':
  - 'Call the decision-makers office and ask to schedule an appointment If 1 or 2 others are truly crucial to your meeting, get their availability before scheduling.) Generally - it should be easy to get a meeting with someone, even if it’s an aide. If you’re getting the brush off- keep calling!' 
  - 'Secure 2-4 people to join you. Make sure you have several perspectives represented - you may want to think about how you represent the decision-makers interests or constituencies in terms of the age, gender, and racial diversity.'
  - 'Create an agenda for your event and share the agenda with your event participants.'
  - 'Practice, practice, practice. Meet with your group and communication via email or phone before the meeting to make sure you are all on the same page. Make sure everyone has their talking points written out. It’s important to have a united front and a clear ask at your meeting.'
  - 'After the meeting - follow up with the decision-maker. Thank them for their time and remind them of your request.'

'Planning meeting':
  - 'Schedule your meeting - make sure you check with key players before the finalize the time.'
  - 'Communicate with other leaders (if there are any) to decide on the agenda.'
  - 'Share the agenda with meeting participants before the meeting.'
  - 'Arrive in the space early to make sure you have everything you need.' 
  - 'Optional: Bring snacks or assign someone to snacks.'
  - 'Optional: Assign a notetaker to take notes and distribute them after the meeting.'
  - 'Optional: Assign a timekeeper to keep things moving.'

'Own event':
  - 'Go to coordinator dashboard and create tasks you think will help to run successful event'
